### ISSUE TITLE
KeyError: 'CFLAGS'

### ISSUE THREAD

**Issue by Hydroholic** [anntzer/pypi2pkgbuild#15]
Hello, whatever package I'm trying to install with `pypi2pkgbuild.py <package>`, I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/pypi2pkgbuild.py", line 1477, in <module>
    sys.exit(main())
  File "/usr/bin/pypi2pkgbuild.py", line 1454, in main
    create_package(name, Options(**vars(args), is_dep=False))
  File "/usr/bin/pypi2pkgbuild.py", line 1253, in create_package
    pkg = dispatch_package_builder(name, options)
  File "/usr/bin/pypi2pkgbuild.py", line 1248, in dispatch_package_builder
    return cls(ref, options)
  File "/usr/bin/pypi2pkgbuild.py", line 912, in __init__
    metadata = _get_metadata(
  File "/usr/bin/pypi2pkgbuild.py", line 505, in _get_metadata
    "CFLAGS": get_makepkg_conf()["CFLAGS"],
KeyError: 'CFLAGS'
```
Any idea why ? How could I fix it ?

PS : I used the package from the AUR, python-pypi2pkgbuild.

**Comment by Hydroholic** [comment]
Well, feeling pretty stupid because using python-pypi2pkgbuild-git instead fixed the bug. Should have posted this issue on the AUR instead. Thanks for this amazing package, have a good day !

**Comment by ctrlcctrlv** [comment]
Hi @Hydroo24. I just hit this issue and am trying to figure out what's gone wrong here.

Is the AUR maintainer of `python-pypi2pkgbuild` negligent and not packing the latest release? The only tagged releases here are v0.0 and v0.1, so is there somewhere else a release above v0.2 would be marked for them to tag?

If not, should @anntzer be tagging a new release post- e49362a66dd078cf75d8b9f4d37a2d3aae3bed1a, which fixed this issue, so that m-pilia on AUR can update it?

Just want to know if this is a "mark outdated" situation on the AUR or a "please make a new release @anntzer". @anntzer should at least tag v0.2 and hopefully the further release I can't find version number of.

**Comment by anntzer** [comment]
0.2 exists on PyPI but predates the relevant commit.  I can tag 0.3 but would rather at least wait for Py3.9 to hit the arch repos (if this takes the same amount of time as for Py3.8 this should happen in the coming days) to avoid having to re-release immediately after if Py3.9 turns out to require additional fixes.  Feel free to ping me again when Py3.9 is `pacman`-installable.

In the meantime, I would suggest using pypi2pkgbuild to pypi2pkgbuild a -git version of itself :)

**Comment by KenMacD** [comment]
Any update on this? I just hit it as well.

**Comment by anntzer** [comment]
Just to clarify, is is just that a new release is needed? (i.e. does master work for you?)

**Comment by ctrlcctrlv** [comment]
In my case you still need to tag 0.3. master works for me.

**Comment by anntzer** [comment]
I tagged v0.3 and released it on PyPI.

**Comment by ctrlcctrlv** [comment]
Great, thanks. Flagged out of date on AUR. Should be updated there soon. If not it'll be orphaned and I'll do it. This issue is finally resolved. :tada:
