### ISSUE TITLE
Package appears to run twice

### ISSUE THREAD

**Issue by hermstadalex** [anntzer/pypi2pkgbuild#4]
I'm not sure if this is actually the intended behavior, but when I run `./pypi2pkgbuild.py -d --pre file:///...`, I get this output:

```INFO:pypi2pkgbuild:Packaging python-kolibri-static 0.1.1rc1.
==> Making package: python-kolibri-static 0.1.1rc1-00 (Fri Feb 24 05:34:43 UTC 2017)
==> WARNING: Skipping dependency checks.
==> Retrieving sources...
  -> Found kolibri_static-0.1.1rc1-py2.py3-none-any.whl
  -> Found LICENSE
==> Validating source files with md5sums...
    kolibri_static-0.1.1rc1-py2.py3-none-any.whl ... Skipped
    LICENSE ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Starting build()...
==> Starting check()...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "python-kolibri-static"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python-kolibri-static 0.1.1rc1-00 (Fri Feb 24 05:36:39 UTC 2017)
==> Making package: python-kolibri-static 0.1.1rc1-00 (Fri Feb 24 05:36:47 UTC 2017)
==> WARNING: Skipping dependency checks.
==> Removing existing $pkgdir/ directory...
==> Entering fakeroot environment...
==> Starting package()...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Removing static library files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "python-kolibri-static"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: python-kolibri-static 0.1.1rc1-00 (Fri Feb 24 05:38:48 UTC 2017)
```

It seems to give the `Finished making: python-kolibri-static 0.1.1rc1-00` message, and then run the same processes again, before exiting. Is this intended behavior?

**Comment by anntzer** [comment]
Yes.  This is because pypi2pkgbuild runs `namcap` on the first built package in order to detect binary dependencies (if one extension module loads another extension module provided by another package, which may be a non-python package).  (Also, if it finds any extension modules -- the presence of which is not so easy to predict otherwise when you are starting from a source package -- it switches the `arch` field from `any` to the correct arch, but this is arguably less important.)  The second run uses `--repackage`, so it should be very quick (it's just rereading the metadata from `PKGBUILD` and re`tar`ing the contents of `./pkg`) as long as you set PKGEXT to `.pkg.tar` (which you should do in general, unless you plan to keep the built packages around).

I guess I could skip this step if no update actually needs to be done...

**Comment by anntzer** [comment]
Pushed a version that skips the rebuild if it appears to be not necessary.

**Comment by hermstadalex** [comment]
Interesting... Thanks for the info! I just ran it, and it looks like the rebuild is necessary in my case.

**Comment by anntzer** [comment]
fwiw kolibri 0.2.0a2 from pypi does not appear to need to rebuild from my own experiments.

**Comment by hermstadalex** [comment]
I see. I was actually building kolibri from a local .whl file, so I'm not sure if that might make the difference.

**Comment by anntzer** [comment]
I downloaded the whl from pypi first, so my build was also local.
